<a href="https://colab.research.google.com/github/rainaa0277/Property_price_prediction-using-Feed-Forward-Neural-Netork/blob/main/ANN_4_Regression_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import tensorflow as tf

In [45]:
# pip install tensorflow==2.0.0

In [46]:
# pip install patool

In [47]:
print(tf.__version__)

2.0.0

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import imutils
import patoolib
import time
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD, Adam

In [49]:
from google.colab import drive
import os

In [50]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
!dir

data_description.txt  sample_submission.csv  test.csv  train.csv

In [52]:
os.chdir("/content/drive/MyDrive/Deep Learning/Practice ANN/ANN 4 - Regression")

In [53]:
!dir

ANN\ 4-\ Regression\ practice.ipynb  DATA-20220221T204035Z-0011
DATA				     DATA-20220221T204035Z-001.zip
DATA-20220221T204035Z-001

In [54]:
patoolib.extract_archive("DATA-20220221T204035Z-001.zip")

patool: Extracting DATA-20220221T204035Z-001.zip ...
patool: running /usr/bin/7z x -o./Unpack_qr9e4n6f -- DATA-20220221T204035Z-001.zip
patool: ... DATA-20220221T204035Z-001.zip extracted to `DATA-20220221T204035Z-0012' (local file exists).

'DATA-20220221T204035Z-0012'

In [55]:
!dir

ANN\ 4-\ Regression\ practice.ipynb  DATA-20220221T204035Z-0011
DATA				     DATA-20220221T204035Z-0012
DATA-20220221T204035Z-001	     DATA-20220221T204035Z-001.zip

In [56]:
os.chdir("DATA")

In [57]:
!dir

data_description.txt  sample_submission.csv  test.csv  train.csv

In [58]:
X = pd.read_csv("train.csv")
y = pd.read_csv("test.csv")

In [59]:
X.head(3)

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500

[3 rows x 81 columns]

In [60]:
y.head(3)

     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal

[3 rows x 80 columns]

In [61]:
X.dropna(axis=1, inplace=True)

In [62]:
X

        Id  MSSubClass MSZoning  ...  SaleType SaleCondition SalePrice
0        1          60       RL  ...        WD        Normal    208500
1        2          20       RL  ...        WD        Normal    181500
2        3          60       RL  ...        WD        Normal    223500
3        4          70       RL  ...        WD       Abnorml    140000
4        5          60       RL  ...        WD        Normal    250000
...    ...         ...      ...  ...       ...           ...       ...
1455  1456          60       RL  ...        WD        Normal    175000
1456  1457          20       RL  ...        WD        Normal    210000
1457  1458          70       RL  ...        WD        Normal    266500
1458  1459          20       RL  ...        WD        Normal    142125
1459  1460          20       RL  ...        WD        Normal    147500

[1460 rows x 62 columns]

In [63]:
X = X.drop(["Id"], axis=1)

In [64]:
X.head(4)

   MSSubClass MSZoning  LotArea  ... SaleType SaleCondition SalePrice
0          60       RL     8450  ...       WD        Normal    208500
1          20       RL     9600  ...       WD        Normal    181500
2          60       RL    11250  ...       WD        Normal    223500
3          70       RL     9550  ...       WD       Abnorml    140000

[4 rows x 61 columns]

In [65]:
numeric_data = X.select_dtypes(include = [np.number])
categorical_data = X.select_dtypes(exclude = [np.number])

In [66]:
numeric_data.columns

Index(['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [67]:
categorical_data.columns

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'Heating',
       'HeatingQC', 'CentralAir', 'KitchenQual', 'Functional', 'PavedDrive',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [68]:
dummy_encoding = pd.get_dummies(categorical_data, drop_first=True)

In [69]:
new_x = pd.concat([numeric_data, dummy_encoding], axis=1)
new_x.head()

   MSSubClass  LotArea  ...  SaleCondition_Normal  SaleCondition_Partial
0          60     8450  ...                     1                      0
1          20     9600  ...                     1                      0
2          60    11250  ...                     1                      0
3          70     9550  ...                     0                      0
4          60    14260  ...                     1                      0

[5 rows x 189 columns]

In [70]:
scale = StandardScaler()

In [73]:
target = new_x["SalePrice"]
scaled_df = scale.fit_transform(new_x.drop("SalePrice", axis=1))

In [75]:
scaled_df

array([[ 0.07337496, -0.20714171,  0.65147924, ..., -0.11785113,
         0.4676514 , -0.30599503],
       [-0.87256276, -0.09188637, -0.07183611, ..., -0.11785113,
         0.4676514 , -0.30599503],
       [ 0.07337496,  0.07347998,  0.65147924, ..., -0.11785113,
         0.4676514 , -0.30599503],
       ...,
       [ 0.30985939, -0.14781027,  0.65147924, ..., -0.11785113,
         0.4676514 , -0.30599503],
       [-0.87256276, -0.08016039, -0.79515147, ..., -0.11785113,
         0.4676514 , -0.30599503],
       [-0.87256276, -0.05811155, -0.79515147, ..., -0.11785113,
         0.4676514 , -0.30599503]])

In [76]:
scaled_df = pd.DataFrame(scaled_df, columns=new_x.columns.drop("SalePrice"))

In [80]:
scaled_df.columns

Index(['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       ...
       'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth',
       'SaleType_WD', 'SaleCondition_AdjLand', 'SaleCondition_Alloca',
       'SaleCondition_Family', 'SaleCondition_Normal',
       'SaleCondition_Partial'],
      dtype='object', length=188)

In [82]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df, target, test_size=0.20, random_state=50)

print(X_train.shape, "X_train")
print(X_test.shape, "X_test")
print(y_train.shape, "y_train")
print(y_test.shape, "y_test")

(1168, 188) X_train
(292, 188) X_test
(1168,) y_train
(292,) y_test

In [87]:
model = Sequential()

model.add(Dense(units = 500, input_shape=(188,), kernel_initializer="normal", activation="relu"))
model.add(Dense(units = 250, kernel_initializer="normal", activation="relu"))
model.add(Dense(units=100, kernel_initializer="normal", activation = "relu"))
model.add(Dense(units=25, kernel_initializer="normal", activation="relu"))
model.add(Dense(units=1, kernel_initializer="normal", activation="linear"))

In [88]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_15 (Dense)             (None, 500)               94500
_________________________________________________________________
dense_16 (Dense)             (None, 250)               125250
_________________________________________________________________
dense_17 (Dense)             (None, 100)               25100
_________________________________________________________________
dense_18 (Dense)             (None, 25)                2525
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 26
=================================================================
Total params: 247,401
Trainable params: 247,401
Non-trainable params: 0
_________________________________________________________________

In [89]:
model.compile(loss = "mean_absolute_error", optimizer="Adam", metrics=["mean_absolute_error"])

In [ ]:
model.fit(X_train,y_train, validation_data=(X_test, y_test), epochs=200, batch_size=50)

In [91]:
predictions = model.predict(X_test)

WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>

In [ ]:
predictions

In [97]:
from sklearn.metrics import r2_score

In [98]:
r2_score(y_test, predictions)

0.8950502032037791

In [101]:
y_test[:5], predictions[:5]

(930     201000
 530     175000
 1291    119500
 1385    125500
 305     305900
 Name: SalePrice, dtype: int64, array([[226896.22],
        [163731.72],
        [ 98293.56],
        [132967.52],
        [299046.22]], dtype=float32))